Merged in a few improvements to the CI (#638)
 - more environment variables are printed
 - use `/Z7` instead of `/Zi /FS` to try avoid intermittent error 
    - `"fatal error c1090: pdb api call failed, error code '23': '("`
    - seems to be related to MSVC, Jenkins and mspdbsrv
 - generate full PDB on windows
 - fail fast to improve overall build cycles
 - use stashing to remove the many azure uploads
 - make sure the git sha was added to the assembly